"""add_job_parameters

Revision ID: 05528c32ec4e
Revises: 
Create Date: 2025-03-18 23:41:12.587953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05528c32ec4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('num_nodes', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('tasks_per_node', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('num_cpus', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('num_gpus', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('time_limit', sa.String(), nullable=True))
    op.drop_column('jobs', 'gpu')
    op.drop_column('jobs', 'cpu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('cpu', sa.INTEGER(), nullable=True))
    op.add_column('jobs', sa.Column('gpu', sa.INTEGER(), nullable=True))
    op.drop_column('jobs', 'time_limit')
    op.drop_column('jobs', 'num_gpus')
    op.drop_column('jobs', 'num_cpus')
    op.drop_column('jobs', 'tasks_per_node')
    op.drop_column('jobs', 'num_nodes')
    # ### end Alembic commands ###