"""Add SLURM monitoring tables

Revision ID: 075dc4526f80
Revises: 07295cd83336
Create Date: 2025-06-04 17:07:09.868671

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "075dc4526f80"
down_revision = "07295cd83336"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create cluster_status table
    op.create_table(
        "cluster_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_connected", sa.Boolean(), nullable=False),
        sa.Column(
            "last_successful_connection", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("last_check", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cluster_status_id"), "cluster_status", ["id"], unique=False
    )

    # Create slurm_job_snapshots table
    op.create_table(
        "slurm_job_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("partition", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("user", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("memory_requested", sa.String(), nullable=True),
        sa.Column("time_used", sa.String(), nullable=True),
        sa.Column("time_left", sa.String(), nullable=True),
        sa.Column("node_count", sa.Integer(), nullable=True),
        sa.Column("node", sa.String(), nullable=True),
        sa.Column("start_time", sa.String(), nullable=True),
        sa.Column("submit_time", sa.String(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False, default=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_slurm_job_snapshots_id"), "slurm_job_snapshots", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_slurm_job_snapshots_job_id"),
        "slurm_job_snapshots",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slurm_job_snapshots_user"),
        "slurm_job_snapshots",
        ["user"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slurm_job_snapshots_user"), table_name="slurm_job_snapshots")
    op.drop_index(
        op.f("ix_slurm_job_snapshots_job_id"), table_name="slurm_job_snapshots"
    )
    op.drop_index(op.f("ix_slurm_job_snapshots_id"), table_name="slurm_job_snapshots")
    op.drop_table("slurm_job_snapshots")
    op.drop_index(op.f("ix_cluster_status_id"), table_name="cluster_status")
    op.drop_table("cluster_status")
    # ### end Alembic commands ###
