"""fix_cluster_stats_table

Revision ID: 0da85dcb8d3b
Revises: 7d7e84783a79
Create Date: 2025-06-05 21:07:05.568777

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0da85dcb8d3b"
down_revision = "7d7e84783a79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster_stats", sa.Column("source", sa.String(), nullable=True))
    op.alter_column(
        "cluster_stats", "used_nodes", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "cluster_stats", "total_nodes", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "cluster_stats", "used_gpus", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "cluster_stats", "total_gpus", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "cluster_stats",
        "timestamp",
        existing_type=sa.DATE(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.drop_column("cluster_stats", "updated_at")
    op.drop_column("ssh_tunnels", "last_used_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ssh_tunnels",
        sa.Column("last_used_at", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "cluster_stats",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "cluster_stats",
        "timestamp",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DATE(),
        nullable=True,
    )
    op.alter_column(
        "cluster_stats", "total_gpus", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "cluster_stats", "used_gpus", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "cluster_stats", "total_nodes", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "cluster_stats", "used_nodes", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("cluster_stats", "source")
    # ### end Alembic commands ###
