"""add cluster stats table

Revision ID: 10_add_cluster_stats
Revises: 09a2736507c5
Create Date: 2025-06-05 19:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '10_add_cluster_stats'
down_revision: Union[str, None] = '09a2736507c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cluster_stats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('used_nodes', sa.Integer(), nullable=False),
        sa.Column('total_nodes', sa.Integer(), nullable=False),
        sa.Column('used_gpus', sa.Integer(), nullable=False),
        sa.Column('total_gpus', sa.Integer(), nullable=False),
        sa.Column(
            'timestamp',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.Column('source', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_cluster_stats_id'),
        'cluster_stats',
        ['id'],
        unique=False
    )
    op.create_index(
        op.f('ix_cluster_stats_timestamp'),
        'cluster_stats',
        ['timestamp'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_cluster_stats_timestamp'),
        table_name='cluster_stats'
    )
    op.drop_index(op.f('ix_cluster_stats_id'), table_name='cluster_stats')
    op.drop_table('cluster_stats')
    # ### end Alembic commands ###
