"""Add is_superuser column to users table

Revision ID: 1d8bc25ab866
Revises: 031067207c3f
Create Date: 2025-03-19 12:15:47.215846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8bc25ab866'
down_revision = '031067207c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###