"""add_port_and_tunnels

Revision ID: 493c7aaaf70f
Revises: 05528c32ec4e
Create Date: 2025-03-18 23:53:49.769493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493c7aaaf70f'
down_revision = '05528c32ec4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'password')
    op.drop_column('jobs', 'port')
    # ### end Alembic commands ###