"""Add is_superuser column to users table

Revision ID: 6457d4ff3953
Revises: 493c7aaaf70f
Create Date: 2025-03-19 00:23:02.955910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '6457d4ff3953'
down_revision = '493c7aaaf70f'
branch_labels = None
depends_on = None


def upgrade():
    # Check if the 'is_superuser' column already exists
    inspector = inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('users')]

    if 'is_superuser' not in columns:
        op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))

    if 'created_at' not in columns:
        op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        op.execute("UPDATE users SET created_at = CURRENT_TIMESTAMP")
        with op.batch_alter_table('users') as batch_op:
            batch_op.alter_column('created_at', nullable=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_superuser')
    op.drop_column('ssh_tunnels', 'updated_at')
    # ### end Alembic commands ###