"""fix_cluster_stats_timestamp_default

Revision ID: 6a0f25957786
Revises: 0da85dcb8d3b
Create Date: 2025-06-05 22:58:47.740052

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a0f25957786"
down_revision = "0da85dcb8d3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Fix timestamp column to have proper default value
    op.alter_column(
        "cluster_stats",
        "timestamp",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove default value from timestamp column
    op.alter_column(
        "cluster_stats",
        "timestamp",
        existing_type=sa.DateTime(timezone=True),
        server_default=None,
        nullable=False,
    )
    # ### end Alembic commands ###
