"""add_internal_port_to_ssh_tunnels

Revision ID: ba669c4c9042
Revises: fd27829d0875
Create Date: 2025-03-26 22:58:05.855088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba669c4c9042'
down_revision = 'fd27829d0875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###