"""add_internal_port_to_ssh_tunnels

Revision ID: fd27829d0875
Revises: cb1d08d165e8
Create Date: 2025-03-26 22:47:09.291961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd27829d0875'
down_revision = 'cb1d08d165e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ssh_tunnels', sa.Column('external_port', sa.Integer(), nullable=True))
    op.add_column('ssh_tunnels', sa.Column('internal_port', sa.Integer(), nullable=True))
    op.add_column('ssh_tunnels', sa.Column('remote_host', sa.String(), nullable=True))
    op.drop_column('ssh_tunnels', 'tunnel_pid')
    op.drop_column('ssh_tunnels', 'local_port')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ssh_tunnels', sa.Column('local_port', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ssh_tunnels', sa.Column('tunnel_pid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ssh_tunnels', 'remote_host')
    op.drop_column('ssh_tunnels', 'internal_port')
    op.drop_column('ssh_tunnels', 'external_port')
    # ### end Alembic commands ###